export const EDITOR_FETCH_DEFAULT = "EDITOR_FETCH_DEFAULT";
export const EDITOR_CHANGE_INPUT = "EDITOR_CHANGE_INPUT";
export const EDITOR_CHANGE_OUTPUT_STYLE = "EDITOR_CHANGE_OUTPUT_STYLE";
export const EDITOR_CHANGE_TAB_SIZE = "EDITOR_CHANGE_TAB_SIZE";
